AWSTemplateFormatVersion: 2010-09-09
Description: >-
  FunctionsToRomanizeJapanese
Transform:
  - AWS::Serverless-2016-10-31

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  JapaneseConverterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: index.handler
      Runtime: nodejs18.x
      Timeout: 30
      MemorySize: 512
      Events:
        ConvertAPI:
          Type: Api
          Properties:
            Path: /convert
            Method: post
